package ru.gotoqa.models;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-17T21:50:43.889+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservices.daehosting.com/ISBN", name = "ISBNServiceSoapType")
@XmlSeeAlso({ObjectFactory.class})
public interface ISBNServiceSoapType {

    /**
     * The test is done by calculation on the first 12 digits and compare the result with the checksum number at the end. You have to pass a 13 digits number.
     */
    @WebMethod(operationName = "IsValidISBN13")
    @RequestWrapper(localName = "IsValidISBN13", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN13")
    @ResponseWrapper(localName = "IsValidISBN13Response", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN13Response")
    @WebResult(name = "IsValidISBN13Result", targetNamespace = "http://webservices.daehosting.com/ISBN")
    public boolean isValidISBN13(
        @WebParam(name = "sISBN", targetNamespace = "http://webservices.daehosting.com/ISBN")
        java.lang.String sISBN
    );

    /**
     * The test is done by calculation on the first 9 digits and compare the result with the checksum number at the end. You have to pass a 10 digits number or 8 digits and an X.
     */
    @WebMethod(operationName = "IsValidISBN10")
    @RequestWrapper(localName = "IsValidISBN10", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN10")
    @ResponseWrapper(localName = "IsValidISBN10Response", targetNamespace = "http://webservices.daehosting.com/ISBN", className = "com.daehosting.webservices.isbn.IsValidISBN10Response")
    @WebResult(name = "IsValidISBN10Result", targetNamespace = "http://webservices.daehosting.com/ISBN")
    public boolean isValidISBN10(
        @WebParam(name = "sISBN", targetNamespace = "http://webservices.daehosting.com/ISBN")
        java.lang.String sISBN
    );
}
